mythodia/modules/accounts/urls.py
from django.urls import path, re_path

from .views import *


app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="sign_up"),
]

mythodia/modules/core/urls.py
from django.urls import path, re_path

from .views import Home

app_name = "core"

urlpatterns = [path("", Home.as_view(), name="home")]

mythodia/modules/wiki/urls.py
from django.urls import path, re_path

from .views import Home

app_name = "wiki"

urlpatterns = [path("", Home.as_view(), name="home")]

mythodia/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings

admin.site.site_header = "Mythodia admin"
admin.site.site_title = "Mythodia admin portal"
admin.site.index_title = "Mythodia admin"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mythodia.modules.core.urls")),
    path("wiki/", include("mythodia.modules.wiki.urls")),
    path("accounts/", include("mythodia.modules.accounts.urls")),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        re_path(r"^__debug__/", include(debug_toolbar.urls)),
        path("__reload__/", include("django_browser_reload.urls")),
    ]

mythodia/modules/accounts/models/account.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from ..managers import AccountManager


class Account(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        _("Email address"),
        unique=True,
        error_messages={"unique": _("A user with that email address already exists.")},
    )
    first_name = models.CharField(_("First name"), max_length=256, blank=True)
    last_name = models.CharField(_("Last name"), max_length=256, blank=True)

    is_staff = models.BooleanField(
        _("Admin status"),
        default=False,
        help_text=_("Designates wheter the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("Active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. Unselect this instead of deleting accounts."
        ),
    )
    is_dm = models.BooleanField(
        _("Dungeon Master"),
        default=False,
        help_text=_("Designates whether this user is a Dungeon Master."),
    )

    date_joined = models.DateTimeField(_("Date joined"), default=timezone.now)

    objects = AccountManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"

    class Meta:
        verbose_name = _("Account")
        verbose_name_plural = _("Accounts")

    @property
    def full_name(self):
        full_name = f"{self.first_name} {self.last_name}"
        return full_name.strip()

    def __str__(self):
        return self.full_name

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

mythodia/modules/characters/models/character.py
from django.db import models
from django.utils.translation import gettext as _


class Character(models.Model):
    player = models.ForeignKey(
        "accounts.Account",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    first_name = models.CharField(_("First name"), max_length=256)
    infix = models.CharField(_("Infix"), max_length=256, null=True, blank=True)
    middle_names = models.CharField(
        _("Middle names"), max_length=256, null=True, blank=True
    )
    last_name = models.CharField(_("Last name"), max_length=256, null=True, blank=True)

    race = models.CharField(_("Race"), max_length=256)
    character_class = models.CharField(_("Class"), max_length=256)
    sub_class = models.CharField(_("Subclass"), max_length=256, null=True, blank=True)

    profile_image = models.ImageField(
        _("Profile image"), help_text=_("Main display image")
    )

    @property
    def full_name(self):
        name_parts = [
            part
            for part in [self.first_name, self.middle_names, self.infix, self.last_name]
            if part
        ]
        return " ".join(name_parts)

    @property
    def race_class_description(self):
        return (
            f"The {self.race} {self.character_class} - {self.sub_class or ''}"
            if self.sub_class
            else f"The {self.race or ''} {self.character_class}"
        )

    def __str__(self):
        return self.full_name

mythodia/modules/dm/models/encounter.py
from django.db import models


class Encounter(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    regions = models.ManyToManyField("dm.Region", blank=True, related_name="encounters")

    @property
    def list_regions(self):
        return ", ".join([region.name for region in self.regions.all()])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Encounter"
        verbose_name_plural = "Encounters"
        ordering = ["name"]

mythodia/modules/dm/models/region.py
from django.db import models


class Region(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Region"
        verbose_name_plural = "Regions"
        ordering = ["name"]

mythodia/modules/dm/models/scenery.py
from django.db import models


class Scenery(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    regions = models.ManyToManyField("dm.Region", blank=True, related_name="scenery")

    @property
    def list_regions(self):
        return ", ".join([region.name for region in self.regions.all()])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Scenery"
        verbose_name_plural = "Scenery"
        ordering = ["name"]

mythodia/modules/wiki/models.py
from django.db import models

# Create your models here.

mythodia/modules/accounts/forms/admin_forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from ..models import Account


class AccountCreationForm(UserCreationForm):
    class Meta:
        model = Account
        fields = ["email"]


class AccountChangeForm(UserChangeForm):
    class Meta:
        model = Account
        fields = ["email"]

mythodia/modules/accounts/forms/login.py
from django.contrib.auth.forms import (
    UsernameField,
    AuthenticationForm as DjangoAuthenticationForm,
)
from django import forms
from django.utils.translation import gettext_lazy as _


class LoginForm(DjangoAuthenticationForm):
    username = UsernameField(
        label=_("Username"), widget=forms.TextInput(attrs={"autofocus": True})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )

mythodia/modules/accounts/forms/sign_up.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.utils.translation import gettext_lazy as _

from ..models import Account


class SignUpForm(UserCreationForm):
    TAILWIND_CLASSES = "w-full px-4 py-2 transition duration-300 border border-gray-300 rounded focus:border-transparent focus:outline-none focus:ring-4 focus:ring-blue-200"

    email = forms.EmailField(
        label=_("Email"),
        widget=forms.EmailInput(
            attrs={
                "autofocus": True,
                "class": TAILWIND_CLASSES,
            }
        ),
        help_text=_(""),
    )
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": TAILWIND_CLASSES,
            }
        ),
        help_text=_(""),
    )
    password2 = forms.CharField(
        label=_("Confirm Password"),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": TAILWIND_CLASSES,
            }
        ),
        help_text=_(""),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Account
        fields = ("email", "password1", "password2")

mythodia/modules/accounts/views/login.py
from django.template import Library
from django.contrib.auth.views import LoginView as DjangoLoginView

from ..forms import LoginForm


class LoginView(DjangoLoginView):
    form_class = LoginForm
    template_name = "accounts/login.html"

    register = Library()

mythodia/modules/accounts/views/sign_up.py
from django.contrib.auth import authenticate, login
from django.views.generic import CreateView

from ..forms import SignUpForm


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = "accounts/sign_up.html"
    success_url = "/"

    def form_valid(self, form):
        res = super().form_valid(form)
        login(self.request, self.object)
        return res

mythodia/modules/characters/views.py
from django.shortcuts import render

# Create your views here.

mythodia/modules/core/views/home.py
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = "core/home.html"

mythodia/modules/wiki/views/home.py
from django.views.generic import TemplateView

from ...characters.models import Character


class Home(TemplateView):
    template_name = "wiki/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        characters = Character.objects.all()
        context["characters"] = characters

        return context

mythodia/templates/core/home.html
{% extends "base.html" %}
{% block page-heading %}
  <span class="text-center block">The universe of mythodia</span>
{% endblock page-heading %}
{% block content %}
  <p class="text-center w-1/2 m-auto mb-4 text-lg leading-none">
    This website is dedicated to my DnD campaign taking place in the universe of Mythodia. Here you will find a wiki containing a lot of different information on the world of mythodia. You will also find a character customizer where you can control what data of your character is shown on the wiki.
  </p>
  <section class="flex flex-wrap flex-col md:flex-row justify-around">
    <div class="text-center mb-4 md:w-1/5">
      <a href="{% url 'wiki:home' %}"
         class="block px-3 py-2 bg-dark-parchment w-fit mb-1 m-auto rounded-md text-black font-bold shadow hover:bg-light-brown hover:text-white transition-all">
        <i class="fa-solid fa-database pr-2"></i>
        Wiki
      </a>
      Descriptions for each player character and their abilities, traits, etc.
    </div>
    {% if user.is_authenticated %}
      <div class="text-center mb-4 md:w-1/5">
        <a class="block px-3 py-2 bg-dark-parchment w-fit mb-1 m-auto rounded-md text-black font-bold shadow hover:bg-light-brown hover:text-white transition-all">
          <i class="fa-solid fa-user-gear pr-2"></i>
          Character manager
        </a>
        Descriptions for each non-player character and their abilities, traits, etc.
      </div>
      <div class="text-center mb-4 md:w-1/5">
        <a class="block px-3 py-2 bg-dark-parchment w-fit mb-1 m-auto rounded-md text-black font-bold shadow hover:bg-light-brown hover:text-white transition-all">
          <i class="fa-solid fa-user-plus pr-2"></i>
          Character creator
        </a>
        A character creator where you can create a character on this website. (You will not get a pdf but you can describe your character)
      </div>
      {% if user.is_dm %}
        <div class="text-center mb-4 md:w-1/5">
          <a class="block px-3 py-2 bg-dark-parchment w-fit mb-1 m-auto rounded-md text-black font-bold shadow hover:bg-light-brown hover:text-white transition-all"><i class="fa-solid fa-gears pr-2"></i>DM data manager</a> This leads to a page where you can manage data for the DM.
        </div>
      {%endif%}
      {% if user.is_staff %}
        <div class="text-center mb-4 md:w-1/5">
          <a class="block px-3 py-2 bg-dark-parchment w-fit mb-1 m-auto rounded-md text-black font-bold shadow hover:bg-light-brown hover:text-white transition-all"><i class="fa-solid fa-gears pr-2"></i>Backoffice</a> This leads to the admin panel where you can manage data.
        </div>
      {% endif %}
    {% else %}
      <div class="text-center mb-4 md:w-1/5">
        <a href="{% url 'accounts:login' %}"
           class="block px-3 py-2 bg-dark-parchment w-fit mb-1 m-auto rounded-md text-black font-bold shadow hover:bg-light-brown hover:text-white transition-all">
          <i class="fa-solid fa-user-gear pr-2"></i>
          Login
        </a>
        Login to access the charater manager and create characters
      </div>
      <div class="text-center mb-4 md:w-1/5">
        <a href="{% url 'accounts:sign_up' %}"
           class="block px-3 py-2 bg-dark-parchment w-fit mb-1 m-auto rounded-md text-black font-bold shadow hover:bg-light-brown hover:text-white transition-all">
          <i class="fa-solid fa-user-plus pr-2"></i>
          Sign-up
        </a>
        Sign-up to access the charater manager and create characters
      </div>
    {% endif %}
  </section>
{% endblock content %}